### ISSUE TITLE
trafgen 的版本是多少

### ISSUE THREAD

**Issue by jimczj** [wenfengshi/ddos-dos-tools#1]
在使用你的[模板](https://github.com/wenfengshi/ddos-dos-tools/blob/master/synflood.trafgen)去运行trafgen --cpp --dev em2 --conf synflood.trafgen --verbose 的时候，会出现错误
trafgen: unrecognized option '--cpp'，请问一下你的trafgen版本是多少

**Comment by wenfengshi** [comment]
> trafgen 0.5.8-rc2 (Ziggomatic), Git id: (none)

`man trafgen`

> -p, --cpp
       Pass the packet configuration to the C preprocessor before reading it into trafgen. This allows #define and #include directives (e.g. to include definitions from system headers)
       to be used in the trafgen configuration file.
